# Generated by Django 5.0.6 on 2024-05-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("datafim", models.DateTimeField()),
                ("data_fim_real", models.DateTimeField()),
            ],
        ),
    ]
