# Generated by Django 5.0.6 on 2024-05-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cadastro",
            name="data_fim_real",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="datafim",
            field=models.DateField(),
        ),
    ]
