# Generated by Django 5.0.6 on 2024-05-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0002_alter_cadastro_data_fim_real_alter_cadastro_datafim"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("dt_nasto", models.DateField(verbose_name="Data de Nascimento")),
                ("doc_rg", models.CharField(max_length=9, verbose_name="RG")),
                ("doc_cpf", models.CharField(max_length=11, verbose_name="CPF")),
                ("funcao", models.CharField(max_length=15, verbose_name="Função")),
                ("dt_admissao", models.DateField(verbose_name="Data de Admissão")),
                (
                    "dt_demissao",
                    models.DateField(null=True, verbose_name="Data de Demissão"),
                ),
                ("login", models.CharField(max_length=10, verbose_name="Login")),
                ("senha", models.CharField(max_length=6, verbose_name="Senha")),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="cadastro",
            options={"ordering": ["datafim"]},
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="datafim",
            field=models.DateField(verbose_name="Data de Nascimento"),
        ),
        migrations.AlterField(
            model_name="cadastro",
            name="titulo",
            field=models.CharField(max_length=50, verbose_name="Nome"),
        ),
    ]
