# Generated by Django 5.0.6 on 2024-05-20 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0003_funcionario_alter_cadastro_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bloco", models.CharField(max_length=5, verbose_name="Bloco")),
                ("andar", models.CharField(max_length=5, verbose_name="Andar")),
                (
                    "numero_apto",
                    models.IntegerField(verbose_name="Numero do Apartamento"),
                ),
                (
                    "telefone_apto",
                    models.CharField(max_length=8, verbose_name="Telefone"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=20, verbose_name="Nome")),
                (
                    "carga_horaria_semanal",
                    models.IntegerField(verbose_name="Carga Horária Semanal"),
                ),
                (
                    "descricao_atividades",
                    models.CharField(
                        max_length=150, verbose_name="Descrição das atividades"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="funcionario",
            name="email",
            field=models.CharField(
                default="none@gmail.com", max_length=30, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="motivo_demissao",
            field=models.CharField(
                default="motivo da demissao",
                max_length=200,
                verbose_name="Motivo da Demissão",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="telefone_apto",
            field=models.CharField(
                default="1234-5678", max_length=8, verbose_name="Telefone"
            ),
        ),
        migrations.CreateModel(
            name="Morador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("dt_nasto", models.DateField(verbose_name="Data de Nascimento")),
                ("doc_rg", models.CharField(max_length=9, verbose_name="RG")),
                ("doc_cpf", models.CharField(max_length=11, verbose_name="CPF")),
                (
                    "apartamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.apartamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Moto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=10, verbose_name="Modelo")),
                ("placa", models.CharField(max_length=8, verbose_name="Placa")),
                ("cor", models.CharField(max_length=10, verbose_name="Cor")),
                (
                    "apartamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.apartamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroMorador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrada", models.DateTimeField(auto_now_add=True)),
                ("data_saida", models.DateTimeField(auto_now_add=True)),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cadastros.funcionario",
                    ),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cadastros.morador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroVisitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrada", models.DateTimeField(auto_now_add=True)),
                ("data_limite", models.DateTimeField(auto_now_add=True)),
                ("data_saida", models.DateTimeField(null=True)),
                (
                    "autorizacao",
                    models.BooleanField(verbose_name="Autorização do Morador"),
                ),
                (
                    "funcionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cadastros.funcionario",
                    ),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cadastros.morador",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QntVagasVisita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qnt_vagas", models.IntegerField()),
                ("vagas_disponiveis", models.IntegerField()),
                (
                    "registro_visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cadastros.registrovisitante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("dt_nasto", models.DateField(verbose_name="Data de Nascimento")),
                ("doc_rg", models.CharField(max_length=9, verbose_name="RG")),
                ("doc_cpf", models.CharField(max_length=11, verbose_name="CPF")),
                ("telefone", models.CharField(max_length=8, verbose_name="Telefone")),
                (
                    "morador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cadastros.morador",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="registrovisitante",
            name="visitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cadastros.visitante"
            ),
        ),
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=10, verbose_name="Modelo")),
                ("placa", models.CharField(max_length=8, verbose_name="Placa")),
                ("cor", models.CharField(max_length=10, verbose_name="Cor")),
                (
                    "apartamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.apartamento",
                    ),
                ),
                (
                    "visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.visitante",
                    ),
                ),
            ],
        ),
    ]
