# Generated by Django 5.0.6 on 2024-05-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_apartamento_cargo_funcionario_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="email",
            field=models.CharField(max_length=30, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="motivo_demissao",
            field=models.CharField(max_length=200, verbose_name="Motivo da Demissão"),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="telefone_apto",
            field=models.CharField(max_length=12, verbose_name="Telefone"),
        ),
    ]
