# Generated by Django 5.0.6 on 2024-05-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_alter_funcionario_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="email",
            field=models.CharField(max_length=100, verbose_name="Email"),
        ),
    ]
