# Generated by Django 5.0.6 on 2024-05-26 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0006_alter_funcionario_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Moto",
        ),
    ]
