# Generated by Django 5.0.6 on 2024-05-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0007_delete_moto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Moto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=10, verbose_name="Modelo")),
                ("placa", models.CharField(max_length=8, verbose_name="Placa")),
                ("cor", models.CharField(max_length=10, verbose_name="Cor")),
                (
                    "morador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.morador",
                    ),
                ),
            ],
        ),
    ]
