# Generated by Django 5.0.6 on 2024-06-02 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0008_moto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carro",
            name="apartamento",
        ),
        migrations.RemoveField(
            model_name="carro",
            name="visitante",
        ),
        migrations.AddField(
            model_name="carro",
            name="morador",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastros.morador",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="confirm_senha",
            field=models.CharField(
                default="senha_confirm", max_length=6, verbose_name="Confirme a senha"
            ),
        ),
        migrations.CreateModel(
            name="CarroVisitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.CharField(max_length=10, verbose_name="Modelo")),
                ("placa", models.CharField(max_length=8, verbose_name="Placa")),
                ("cor", models.CharField(max_length=10, verbose_name="Cor")),
                (
                    "visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cadastros.visitante",
                    ),
                ),
            ],
        ),
    ]
