# Generated by Django 5.0.6 on 2024-06-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0009_remove_carro_apartamento_remove_carro_visitante_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registromorador",
            name="data_saida",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
