# Generated by Django 5.0.6 on 2024-06-22 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0011_alter_registrovisitante_data_limite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cargo",
        ),
        migrations.AlterModelOptions(
            name="funcionario",
            options={"ordering": ["nome"], "verbose_name_plural": "funcionarios"},
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="confirm_senha",
            field=models.CharField(
                default="senha_confirm", max_length=20, verbose_name="Confirme a senha"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="senha",
            field=models.CharField(max_length=20, verbose_name="Senha"),
        ),
        migrations.AlterField(
            model_name="registromorador",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registrovisitante",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
