# Generated by Django 5.0.6 on 2024-06-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0011_alter_registrovisitante_data_limite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="funcionario",
            options={"ordering": ["nome"], "verbose_name_plural": "funcionarios"},
        ),
    ]
