# Generated by Django 5.0.6 on 2024-06-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0011_alter_registrovisitante_data_limite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cargo",
        ),
        migrations.AlterModelOptions(
            name="funcionario",
            options={"ordering": ["nome"], "verbose_name_plural": "funcionarios"},
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="confirm_senha",
            field=models.CharField(
                default="senha_confirm", max_length=20, verbose_name="Confirme a senha"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="senha",
            field=models.CharField(max_length=20, verbose_name="Senha"),
        ),
    ]
