# Generated by Django 5.0.6 on 2024-06-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0012_alter_funcionario_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="confirm_senha",
            field=models.CharField(
                default="senha_confirm", max_length=20, verbose_name="Confirme a senha"
            ),
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="senha",
            field=models.CharField(max_length=20, verbose_name="Senha"),
        ),
    ]
