# Generated by Django 5.0.6 on 2024-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0012_delete_cargo_alter_funcionario_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitante",
            name="morador",
        ),
        migrations.AddField(
            model_name="visitante",
            name="status",
            field=models.CharField(
                choices=[("A", "Ativo(a)"), ("S", "Suspenso(a)"), ("I", "Inativo(a)")],
                default="A",
                max_length=1,
            ),
        ),
    ]
