# Generated by Django 5.0.6 on 2024-06-22 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0013_remove_visitante_morador_visitante_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="morador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cadastros.morador"
            ),
        ),
    ]
