# Generated by Django 5.0.6 on 2024-06-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0014_alter_carro_morador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funcionario",
            name="confirm_senha",
            field=models.CharField(max_length=20, verbose_name="Confirme a senha"),
        ),
    ]
