# Generated by Django 5.0.6 on 2024-06-22 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0015_alter_funcionario_confirm_senha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registromorador",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cadastros.funcionario",
            ),
        ),
    ]
