# Generated by Django 5.0.6 on 2024-06-22 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0016_alter_registromorador_funcionario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrovisitante",
            name="data_limite",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="registrovisitante",
            name="funcionario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cadastros.funcionario",
            ),
        ),
    ]
