# Generated by Django 5.0.6 on 2024-06-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0017_alter_registrovisitante_data_limite_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrovisitante",
            name="data_limite",
            field=models.DateTimeField(),
        ),
    ]
