# Generated by Django 5.0.6 on 2024-06-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0018_alter_registrovisitante_data_limite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrovisitante",
            name="funcionario",
        ),
    ]
