# Generated by Django 5.0.6 on 2024-06-25 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0019_remove_registrovisitante_funcionario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registromorador",
            name="funcionario",
        ),
    ]
