# Generated by Django 5.0.6 on 2024-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0020_remove_registromorador_funcionario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrovisitante",
            options={"ordering": ["data_limite"]},
        ),
        migrations.AlterField(
            model_name="registrovisitante",
            name="data_limite",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
