# Generated by Django 5.0.6 on 2024-06-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0021_alter_registrovisitante_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registromorador",
            options={"ordering": ["data_saida"]},
        ),
    ]
