# Generated by Django 5.0.6 on 2024-06-26 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0022_alter_registromorador_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrovisitante",
            name="data_ligacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registrovisitante",
            name="ligacao",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registrovisitante",
            name="autorizacao",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Autorização do Morador"
            ),
        ),
        migrations.AlterField(
            model_name="registrovisitante",
            name="visitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cadastros.visitante"
            ),
        ),
    ]
