# Generated by Django 5.0.6 on 2024-06-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0023_registrovisitante_data_ligacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrovisitante",
            name="autorizacao",
            field=models.BooleanField(
                default=True, verbose_name="Autorização do Morador"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="registrovisitante",
            name="ligacao",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="Ligou para o Visitante?"
            ),
            preserve_default=False,
        ),
    ]
