# Generated by Django 5.0.6 on 2024-06-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0025_alter_registrovisitante_ligacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrovisitante",
            options={"ordering": ["data_limite", "data_saida"]},
        ),
        migrations.RemoveField(
            model_name="qntvagasvisita",
            name="registro_visitante",
        ),
    ]
