# Generated by Django 5.0.6 on 2024-06-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0026_alter_registrovisitante_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrovisitante",
            name="esta_de_carro",
            field=models.BooleanField(default=False, verbose_name="Está de carro?"),
            preserve_default=False,
        ),
    ]
