# Generated by Django 5.0.6 on 2024-06-28 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0028_alter_apartamento_telefone_apto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carro",
            name="morador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cadastros.morador"
            ),
        ),
        migrations.AlterField(
            model_name="registromorador",
            name="morador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cadastros.morador"
            ),
        ),
        migrations.AlterField(
            model_name="registrovisitante",
            name="morador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cadastros.morador"
            ),
        ),
    ]
