# Generated by Django 5.0.6 on 2024-06-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colaborador",
            name="dt_nasto",
        ),
    ]
