# Generated by Django 5.0.6 on 2024-06-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_remove_colaborador_dt_nasto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colaborador",
            name="dt_admissao",
        ),
        migrations.RemoveField(
            model_name="colaborador",
            name="login",
        ),
        migrations.AddField(
            model_name="colaborador",
            name="dt_nasto",
            field=models.DateField(null=True, verbose_name="Data de Nascimento"),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="usuario",
            field=models.CharField(max_length=15, null=True, verbose_name="usuario"),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("ADM", "Administrador(a)"),
                    ("PTR", "Porteiro(a)"),
                    ("SDC", "Síndico(a)"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="doc_cpf",
            field=models.CharField(max_length=11, null=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="doc_rg",
            field=models.CharField(max_length=9, null=True, verbose_name="RG"),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="nome",
            field=models.CharField(max_length=50, null=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="colaborador",
            name="telefone",
            field=models.CharField(max_length=12, null=True, verbose_name="Telefone"),
        ),
    ]
