# Generated by Django 5.0.6 on 2024-06-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_colaborador_dt_demissao_colaborador_dt_nasto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colaborador",
            name="dt_admissao",
        ),
        migrations.RemoveField(
            model_name="colaborador",
            name="dt_demissao",
        ),
        migrations.RemoveField(
            model_name="colaborador",
            name="login",
        ),
        migrations.RemoveField(
            model_name="colaborador",
            name="motivo_demissao",
        ),
        migrations.AddField(
            model_name="colaborador",
            name="usuario",
            field=models.CharField(max_length=15, null=True, verbose_name="usuario"),
        ),
    ]
