# Generated by Django 5.0.6 on 2024-06-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_remove_colaborador_dt_admissao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="telefone",
            field=models.CharField(max_length=20, null=True, verbose_name="Telefone"),
        ),
    ]
