# Generated by Django 5.0.6 on 2024-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0005_alter_colaborador_cargo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("ADM", "Administrador(a)"),
                    ("PTR", "Porteiro(a)"),
                    ("SDC", "Síndico(a)"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
